### ISSUE TITLE
Flexibility of content types linked to service pages

### ISSUE THREAD

**Issue by carolynbowes** [massgov/feature-requests#106]
I would like more flexibility in the types of content that can be linked to non-featured items on the service page. Users are leaving feedback that they can't find things because related items aren't immediately obvious.

JIRA ticket #: DP-9495

**Comment by joeg8612** [comment]
Last night we implemented a change that allows Guides and Forms in the "All other tasks" section. It also allows court rules, regulation, advisory, decision, executive order in the "What you need to know" section.
