### ISSUE TITLE
Ability to remove "Feedback" by page

### ISSUE THREAD

**Issue by npcox** [massgov/feature-requests#131]
Ability to remove the Tell Us What You Think feedback box from certain pages. For the RMV, customers are using this link to report an issue, seek assistance, asking a specific question, etc. and are expecting a response instead of using the Ask the RMV feedback form. 

OR

Include email if one is provided on the EOTSS feedback CMS page so we can respond to customers if needed.

**Comment by m-aiello** [comment]
I'm not sure what the best solution is. I will echo that we get lots of feedback with personal contact information. And yet sometimes we do get feedback that helps with content quality. So I am torn over the usefulness of it to improve the site vs. how some people expect it to be a "contact" box.

I know there is language there that says:

> "We use your feedback to help us improve this site but we are not able to respond directly. Please do not include personal or contact information. If you need a response, please locate the contact information elsewhere on this page or in the footer."

But people seem to miss that or ignore it. Maybe if that language existed as a "pop-up" that people had to close before they can even start typing?

Or what if, on each page, this feedback box could also automatically pull information from the contact info (if there is contact info included on said page)?

**Comment by npcox** [comment]
Michael, agree that if we could retrieve/display contact (email) so we can respond when needed. Also, would like to see timestamp of when posted in case customer is reporting a system issue.

**Comment by joeg8612** [comment]
We are working now on a feature that lets organizations choose how they want the feedback feature to be displayed on their pages. You will be able to keep it essentially the same as now, offer a contact link after the message is submitted or allow the visitor to enter in contact information so they can get a response. This will rollout in January 2019.

**Comment by joeg8612** [comment]
Our feature that launched several months ago allows organizations to decide how to handle feedback on their pages. You can choose to collect contact information with the "Did you find" information or provide a link to a contact page after the feedback is submitted. We want to avoid configuring pages so that the feedback can't be provided as we would then lose the opportunity to measure or improve the performance of those pages.
