### ISSUE TITLE
Downloadable Listing of Pages in Drupal into Excel spreadsheet or other format

### ISSUE THREAD

**Issue by swunderlee** [massgov/feature-requests#140]
**Is your feature request related to a problem? Please describe.**
There is no way to see one list of all the content our agency has created

**Describe the solution you'd like**
I would like a way to download a list of all of the pages that an Organization has created

**Reference**
REQ0042459

**Comment by npcox** [comment]
Would also like a way to download feedback and documents too.

**Comment by alarrimore** [comment]
We have this type of request starting to come in on a regular basis now.

Would like an exportable view of content by organization - show title, ID, Type, Publication Status, Author

**Comment by lmirabile** [comment]
This work was completed and released Oct. 3 2018 (release #136.0). Jira ticket for reference: DP-10263.
