### ISSUE TITLE
Design: Service Page title and short description cut off depending on screen size

### ISSUE THREAD

**Issue by m-aiello** [massgov/feature-requests#145]
**Is your feature request related to a problem? Please describe.**
Some service pages have longer titles. Depending on the screen/window size, the page will sometimes format the title and short description in such a way that they may be cut off from view. See attached example, as pointed out by a program contact.
![service page text](https://user-images.githubusercontent.com/42180733/45172632-e439a900-b1d3-11e8-9365-d03bb7ff52c3.PNG)

**Describe the solution you'd like**
Have the system better resize the title and short description text so it always fits the window size.

**Comment by m-aiello** [comment]
Another example, where part of the title is cut off as well as part of the short description.
![service-page-cutoff](https://user-images.githubusercontent.com/42180733/45566606-2b9fe500-b825-11e8-8925-58744c9d9fec.PNG)

**Comment by joeg8612** [comment]
Adding URL https://www.mass.gov/about-the-board-of-certification-of-community-health-workers

**Comment by joeg8612** [comment]
Our recent header change has largely fixed this issue.
