### ISSUE TITLE
Exporting document lists from CMS

### ISSUE THREAD

**Issue by jpcohen** [massgov/feature-requests#159]
I am working with the Department of Early Education and Care (EEC), and trying to review all the documents ever uploaded to the CMS by or on behalf of EEC. That is, rather than looking for one specific document, we're looking for whole categories of documents using multiple search queries and we're not sufficiently confident that we haven't missed something.

It would be valuable to be able to generate an exportable list of documents (.xlsx or .csv or similar) that can be sorted and manipulated more dynamically, outside of the CMS. Ideally a report that includes the title, file name, 

If this could be added as a feature it would very helpful! Thank you!

ServiceNow ticket number: REQ0045813

**Comment by joeg8612** [comment]
This is implemented.  There is a "CSV" icon at the bottom of the document list that will let you download a full list of all documents matching the filter criteria.
