### ISSUE TITLE
Add help text to warn users to save before using Preview

### ISSUE THREAD

**Issue by swunderlee** [massgov/feature-requests#168]
**Is your feature request related to a problem? Please describe.**
We have noticed that if an Author Previews changes before Saving them the changes disappear and must be entered again.

**Describe the solution you'd like**
Could a warning message be added to alert the user that their changes will be lost and they must save the changes first?

**Comment by joeg8612** [comment]
I just tested and I'm not seeing this issue any longer. If you are still experiencing this, please comment below with details and an example.  Thanks.

**Comment by swunderlee** [comment]
Hi,

I just verified with one of my Authors, this does not seem to be happening now.

Thanks,
Sue

**Comment by joeg8612** [comment]
Great, closing this issue.  Thanks.
