### ISSUE TITLE
Add Guide pages to "What would you like to do?" on Service pages

### ISSUE THREAD

**Issue by maleonard01** [massgov/feature-requests#170]
**Problem:**
We have begun to build out complex how-to pages into Guide pages, but we cannot properly link Guides to "What would you like to do?" on Service page. This hurts our findability score and user experience (relationship indicator needed at the top of the Guide). 

**Solution:**
Allow Guides in the auto-complete fields for "All other tasks"

**Additional context**
Guides can be actionable and EOTSS Content Strategists recommended that we turn complex How-tos into Guides. They are not always a "First Time?" item and some Services need more than 1 Guide.

**Comment by joeg8612** [comment]
This was implemented last night.
