### ISSUE TITLE
Add copying content

### ISSUE THREAD

**Issue by lyndoer** [massgov/feature-requests#177]
If you need to add an entire year's worth of something like an event, you have to do each one individually.

Please add the ability to copy content so, in the example described above, an event can be copied 12 times and only the date would need to be changed in the CMS.

**Comment by shaed333** [comment]
Thank you for your feedback. We know that this would be a valuable feature, but there are technical challenges that make it difficult to complete right now. This is also an existing issue under consideration. You are welcome to "thumbs up" and add/copy or paste your comments in the original request - https://github.com/massgov/feature-requests/issues/30. 
We will close this request as a duplicate. Thank you very much for your input.

**Comment by joeg8612** [comment]
closed as duplicate, see issue 30.
