### ISSUE TITLE
Can four events, instead of two, be displayed? 

### ISSUE THREAD

**Issue by parkjoesungjun** [massgov/feature-requests#179]
I would like to see more than two events, preferably four events in my Organization page under Upcoming Events. Because one event with three events on the same day currently can not be displayed. Thank you

https://www.mass.gov/orgs/civil-service/events?_page=1

**Comment by joeg8612** [comment]
Hi Sungjun,
We have a ticket for this request already open.  I will put your note on that ticket and close this one as a duplicate. Feel free to upvote the other issue.
https://github.com/massgov/feature-requests/issues/31
Thanks,
Joe

**Comment by parkjoesungjun** [comment]
Thank you for the update, Joe!

Sungjun Park
617-878-9770

CONFIDENTIALITY NOTICE -  This email is intended only for the person(s) named in the message header.  Unless otherwise indicated, it contains information that is confidential, privileged and/or exempt from disclosure under applicable law.  If you have received this message in error, please notify the sender of the error and delete the message immediately. Thank you.
