### ISSUE TITLE
Need a way to bulk edit documents to add labels

### ISSUE THREAD

**Issue by ma-dph-beh** [massgov/feature-requests#184]
As part of the transition documents where imported without labels. It would be nice to utilize curated lists to pull these together but none of them have labels assigned to them.  It would be great to have a way to filter to a list of documents, by searching the organization and key words in the title, then to be able to add a label, or labels, to all the documents returned in the query.  An alternative solution might be a way to request an exported list of our documents with the Drupal id.  We could then add the appropriate labels into a column and submitted it back to the Mass Digital team to process as a data update. 

While we can edit each document, to add the labels to them, in some cases there are hundred that would need the same edit and editing each one individually would not be productive.

**Comment by joeg8612** [comment]
We don't have a way to support this for authors but we have some limited ways to do this on our end. Please make a servicenow request with link to a search in Drupal that shows the documents.
