### ISSUE TITLE
Feature request: Feedback Manager Export by Date Range

### ISSUE THREAD

**Issue by irisamelia-TRE** [massgov/feature-requests#185]
As a user, I would like to export comments from the feedback manager filtered by date range. At this time I believe ALL data would be exported every time I use the Feedback Manager's export feature. So:

- Select date range (February 1, 2019 to March 11, 2019) -- so select a start date and end date

- Export results; feedback would be sorted by date (preferably most recent to oldest)

**Comment by joeg8612** [comment]
This has been implemented!
