### ISSUE TITLE
White Space in iFrames

### ISSUE THREAD

**Issue by kelkins231** [massgov/feature-requests#244]
**Is your feature request related to a problem? Please describe.**
There is too much white space appearing when I add an iFrame from "Infogram". Also a black bar appears that is not necessary
![Screenshot 2022-12-09 100104](https://user-images.githubusercontent.com/104406118/206731638-1ade0945-0433-4feb-a8ad-62ed4cc41cc1.png)
.

**Describe the solution you'd like**
I'd like less white space to occur - or a way to preview as I change the parameters. Do not have black bar appear.

**Additional context**
n/a
**Reference**
n/a

**Comment by joeg8612** [comment]
Please make a ServiceNow request so we can try to assist with this.
