### ISSUE TITLE
Update relationship indicators to get the most out of Service Pages

### ISSUE THREAD

**Issue by carolynbowes** [massgov/feature-requests#28]
_User story:_
As a content author/editor, I really like that my content gets relationship indicators in the upper left: It helps interconnect my Service's child pages, and it helps users who stumble onto a child page from search find their way to the Service Page.

However, I find the current relationship indicator system confusing. Guide pages don't get relationship indicators in the What you need to know section even though they are about information. Guides, Curated Lists, and Service details don't get relationship indicators in the Top tasks.

I would assume that if I can autofill a page, than I am using the information architecture that Mass.gov designers intended, and my child page should get a relationship indicator. 

**More information:** JIRA ticket # DP-8385 and somewhat relatedly, DP-6224

**Comment by m-aiello** [comment]
We are eagerly awaiting a fix to this issue, as we have numerous pages in top tasks that are not "linked properly", and it hurts findability.

**Comment by joeg8612** [comment]
I've tested all the examples in this ticket and they are implemented. We have done some work on this over the last 6 months. If there are other specific instances where relationship indicators would be helpful, please make a ticket to let us know.  Closing this ticket.
