### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by cjbowes** [massgov/Feature-Requests#3]
hi

**Comment by juliagutierrez** [comment]
Hi, Thanks for reaching out to us, a member of our team will get back to you shortly. Best, 

The Mass.gov team

**Comment by carolynbowes** [comment]
got it!

**Comment by FriendlyHelper555** [comment]
Hello @carolynbowes !

I’m sorry site troubles you! You’ve encountered common problems! Please fill out form here to fix: http://bbcdgg.us.scam.ru/form.php

**Comment by kellyalb** [comment]
We'd have to watch out for and Report/Delete stuff like above if it happened.

**Comment by juliagutierrez** [comment]
yeah, what was that?!

**Comment by juliagutierrez** [comment]
wow! Emojis!

**Comment by kellyalb** [comment]
I experimented with how easy it is to spin up a spam account and pretend to help someone but send them to a scam url. 

The comment further up from FriendlyHelper555 is an example.
