### ISSUE TITLE
Allow content authors to duplicate an existing page

### ISSUE THREAD

**Issue by carolynbowes** [massgov/feature-requests#30]
**User story:** 
As a content author, I want to be able to duplicate an existing page that has similar content to save time when I create a new page. I would also like to create a "template" of a typical page, with the standard subheads and sections already created, and duplicate that when creating any page, also to save time and increase consistency and accuracy.

**More information:** JIRA ticket # DP-1154

**Comment by lacedog** [comment]
We were able to do this in Percussion. We could copy a page and save it as a copy. All the sidebar and bottom content would already be there, saving a lot of time when you are making many pages based on the same basic template. Allow us to copy a page.

**Comment by joeg8612** [comment]
This has been implemented!
