### ISSUE TITLE
Flexible number of event previews

### ISSUE THREAD

**Issue by carolynbowes** [massgov/feature-requests#31]
**User story:**
As a content author, I would like the option to preview more than two events if more exist.

**JIRA ticket #:** DP-8201

**Comment by m-aiello** [comment]
At DPH, some higher-level org pages will display multiple events from across their lower-level orgs. Being able to see more would help increase visibility.

**Comment by joeg8612** [comment]
We received this comment from HRD:
I would like to see more than two events, preferably four events in my Organization page under Upcoming Events. Because one event with three events on the same day currently can not be displayed. Thank you
https://www.mass.gov/orgs/civil-service/events?_page=1

**Comment by joeg8612** [comment]
This has been implemented.  You can choose to display up to 8 events on an organization or service page now.
