### ISSUE TITLE
Add underline function to rich text areas

### ISSUE THREAD

**Issue by carolynbowes** [massgov/feature-requests#52]
**Use case:**
We need an underline function when quoting legal cases.

**JIRA ticket #:** DP-9038

**Comment by joeg8612** [comment]
I worry that this will be confused with a link.

**Comment by juliagutierrezp** [comment]
I worry about that too.

**Comment by joeg8612** [comment]
It is best practice not to use underline for anything except links on the web.  Closing this as no action.
