### ISSUE TITLE
My page isn't working 

### ISSUE THREAD

**Issue by juliagutierrez** [massgov/Feature-Requests#6]
Hi, my page doesn't work. Help me. it's urgent.

**Comment by FriendlyHelper555** [comment]
Hi @juliagutierrez 

I would be happy to assist you, 

I’m sorry site troubles you! You’ve encountered common problems! Please fill out form here to fix: http://bbcdgg.us.scam.ru/form.php

**Comment by kellyalb** [comment]
We'd have to watch out for and Report/Delete stuff like above if it happened.

**Comment by kellyalb** [comment]
Hey @juliagutierrez , I've reproduced your issue and am putting it on deck for continued support. We will followup soon.

**Comment by kellyalb** [comment]
Hi @juliagutierrez, I'm going to be investigating this. I've made a setting change to your account. Could you try archiving the page and then republishing it? Let me know the results!

Thanks!
The Mass.gov team
