### ISSUE TITLE
Add related links to curated lists

### ISSUE THREAD

**Issue by joeg8612** [massgov/feature-requests#89]
Feature request to add related links on the side and a more about link in the jump link

Similar to service detail page related links: https://www.mass.gov/service-details/massachusetts-state-retirement-board-meetings-msrb

**Reference**
JIRA DP-6388

**Comment by m-aiello** [comment]
Note: I see this is an identical request with #34. We may want to combine them.

**Comment by joeg8612** [comment]
This has been implemented.
